pipeline {
agent any 
stages {
    stage('remove old container') {
        steps {
           sh 'docker container rm -f frontend'
      }
    }
    stage('Image Build') {
        steps {
           sh 'cd webapp && docker build -t web .'
      }
    }
    stage('Running Container') {
        steps {
           sh 'docker container run -dt --name frontend --network lmsnetwork -p 80:80 web'
      }
    }
    stage('build status') {
        steps {
           sh 'echo backend deployed'
      }
    }
  }
}
