name: Build
on: workflow_dispatch
jobs:
  sonar:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
